package ExceptionHandling;

public class Example1 {


	public static void ex1(){
		try {
			System.out.println("Entered Try Block");
			String[] x1 = {"a","b"}; //Size=2 [indexes: 0,1]
			//	x1[0] = "abc"; // Exception occurred because Array index started from -1 where as it should be 0
			System.out.println("Length of array = "+x1.length);

			for (int i = 0; i < x1.length; i++) {
				System.out.println(x1[i]);
 			}
		} catch (Exception e) {
			System.out.println("Entered Catch Block");
  			e.printStackTrace();
			throw e;
		}

	}


	public static void main(String[] args) {

		ex1();

	}

}
